In [18]:
import pandas as pd
import numpy as np

from sklearn import preprocessing
from sklearn.cluster import KMeans

In [19]:
data = pd.read_csv('./team_cluster_data.csv',encoding = 'gbk')
print(data,type(data))
x_train = data.iloc[:,1:].values
print(x_train,type(x_train))

        国家  2019国际排名  2018世界杯排名  2015亚洲杯排名
0       中国        73         40          7
1       日本        60         15          5
2       韩国        61         19          2
3       伊朗        34         18          6
4       沙特        67         26         10
5      伊拉克        91         40          4
6      卡塔尔       101         40         13
7      阿联酋        81         40          6
8   乌兹别克斯坦        88         40          8
9       泰国       122         40         17
10      越南       102         50         17
11      阿曼        87         50         12
12      朝鲜       110         50         14
13      印尼       164         50         17
14      澳洲        40         30          1
15     叙利亚        76         40         17
16      约旦       118         50          9
17     科威特       160         50         15 <class 'pandas.core.frame.DataFrame'>
[[ 73  40   7]
 [ 60  15   5]
 [ 61  19   2]
 [ 34  18   6]
 [ 67  26  10]
 [ 91  40   4]
 [101  40  13]
 [ 81  40   6]
 [ 88  40   8]
 [122  40 

In [20]:
# featuure scalling
min_max_scaler=preprocessing.MinMaxScaler()
x_train = min_max_scaler.fit_transform(x_train)
print(x_train)

[[0.3        0.71428571 0.375     ]
 [0.2        0.         0.25      ]
 [0.20769231 0.11428571 0.0625    ]
 [0.         0.08571429 0.3125    ]
 [0.25384615 0.31428571 0.5625    ]
 [0.43846154 0.71428571 0.1875    ]
 [0.51538462 0.71428571 0.75      ]
 [0.36153846 0.71428571 0.3125    ]
 [0.41538462 0.71428571 0.4375    ]
 [0.67692308 0.71428571 1.        ]
 [0.52307692 1.         1.        ]
 [0.40769231 1.         0.6875    ]
 [0.58461538 1.         0.8125    ]
 [1.         1.         1.        ]
 [0.04615385 0.42857143 0.        ]
 [0.32307692 0.71428571 1.        ]
 [0.64615385 1.         0.5       ]
 [0.96923077 1.         0.875     ]]


In [23]:
# KMeans
kmeans = KMeans(n_clusters = 3)
kmeans.fit(x_train)
y_cluster = kmeans.predict(x_train)

In [24]:
y_cluster

array([2, 1, 1, 1, 1, 2, 0, 2, 2, 0, 0, 0, 0, 0, 1, 0, 2, 0], dtype=int32)

In [27]:
res = pd.concat((data,pd.DataFrame(y_cluster)), axis = 1)

In [30]:
res.rename({0:'聚类结构'},axis = 1,inplace=True)
res

国家  2019国际排名  2018世界杯排名  2015亚洲杯排名  聚类结构
0       中国        73         40          7     2
1       日本        60         15          5     1
2       韩国        61         19          2     1
3       伊朗        34         18          6     1
4       沙特        67         26         10     1
5      伊拉克        91         40          4     2
6      卡塔尔       101         40         13     0
7      阿联酋        81         40          6     2
8   乌兹别克斯坦        88         40          8     2
9       泰国       122         40         17     0
10      越南       102         50         17     0
11      阿曼        87         50         12     0
12      朝鲜       110         50         14     0
13      印尼       164         50         17     0
14      澳洲        40         30          1     1
15     叙利亚        76         40         17     0
16      约旦       118         50          9     2
17     科威特       160         50         15     0